# -*- coding: utf-8 -*-
"""imerg_daily_rainfall_download.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KebHNHvXB08PAWVS9PXjWUBHaUmKwNOf
"""

!pip install netCDF4

"""Register for a free NASA Earthdata account at https://urs.earthdata.nasa.gov/

- Replace the credentials in the code:

- username = "YOUR_EARTHDATA_USERNAME"
- password = "YOUR_EARTHDATA_PASSWORD"


- For the subset file (like your .SUB.nc4), you need to use the GES DISC subset tool instead:

- Go to https://disc.gsfc.nasa.gov/
- Search for "GPM_3IMERGDL"
- Select your date range and spatial subset (Lon: 50-110, Lat: -10 to 40)
- Download the subset links file

## Earth login data access
- https://disc.gsfc.nasa.gov/earthdata-login
"""

from getpass import getpass
import os

username = input("Earthdata username: ")
password = getpass("Earthdata password: ")

with open("/root/.netrc", "w") as f:
    f.write(f"machine urs.earthdata.nasa.gov login {username} password {password}")

os.chmod("/root/.netrc", 0o600)

print("✅ .netrc configured")
# username: lakshitha061
# password: (my_pwd#)12

!touch /root/cookies.txt

# set all links as follow array
links = [
    "https://gpm1.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FGPM_L3%2FGPM_3IMERGDL.07%2F2025%2F09%2F3B-DAY-L.MS.MRG.3IMERG.20250901-S000000-E235959.V07B.nc4&VARIABLES=precipitation&FORMAT=bmM0Lw&BBOX=-10%2C50%2C40%2C110&SHORTNAME=GPM_3IMERGDL&DATASET_VERSION=07&LABEL=3B-DAY-L.MS.MRG.3IMERG.20250901-S000000-E235959.V07B.nc4.SUB.nc4&VERSION=1.02&SERVICE=L34RS_GPM",

    "https://gpm1.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FGPM_L3%2FGPM_3IMERGDL.07%2F2025%2F09%2F3B-DAY-L.MS.MRG.3IMERG.20250902-S000000-E235959.V07B.nc4&VARIABLES=precipitation&FORMAT=bmM0Lw&BBOX=-10%2C50%2C40%2C110&SHORTNAME=GPM_3IMERGDL&DATASET_VERSION=07&LABEL=3B-DAY-L.MS.MRG.3IMERG.20250902-S000000-E235959.V07B.nc4.SUB.nc4&VERSION=1.02&SERVICE=L34RS_GPM",

    "https://gpm1.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FGPM_L3%2FGPM_3IMERGDL.07%2F2025%2F09%2F3B-DAY-L.MS.MRG.3IMERG.20250903-S000000-E235959.V07B.nc4&VARIABLES=precipitation&FORMAT=bmM0Lw&BBOX=-10%2C50%2C40%2C110&SHORTNAME=GPM_3IMERGDL&DATASET_VERSION=07&LABEL=3B-DAY-L.MS.MRG.3IMERG.20250903-S000000-E235959.V07B.nc4.SUB.nc4&VERSION=1.02&SERVICE=L34RS_GPM",

    "https://gpm1.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FGPM_L3%2FGPM_3IMERGDL.07%2F2025%2F09%2F3B-DAY-L.MS.MRG.3IMERG.20250904-S000000-E235959.V07B.nc4&VARIABLES=precipitation&FORMAT=bmM0Lw&BBOX=-10%2C50%2C40%2C110&SHORTNAME=GPM_3IMERGDL&DATASET_VERSION=07&LABEL=3B-DAY-L.MS.MRG.3IMERG.20250904-S000000-E235959.V07B.nc4.SUB.nc4&VERSION=1.02&SERVICE=L34RS_GPM",

    "https://gpm1.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FGPM_L3%2FGPM_3IMERGDL.07%2F2025%2F09%2F3B-DAY-L.MS.MRG.3IMERG.20250905-S000000-E235959.V07B.nc4&VARIABLES=precipitation&FORMAT=bmM0Lw&BBOX=-10%2C50%2C40%2C110&SHORTNAME=GPM_3IMERGDL&DATASET_VERSION=07&LABEL=3B-DAY-L.MS.MRG.3IMERG.20250905-S000000-E235959.V07B.nc4.SUB.nc4&VERSION=1.02&SERVICE=L34RS_GPM",

    "https://gpm1.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FGPM_L3%2FGPM_3IMERGDL.07%2F2025%2F09%2F3B-DAY-L.MS.MRG.3IMERG.20250906-S000000-E235959.V07B.nc4&VARIABLES=precipitation&FORMAT=bmM0Lw&BBOX=-10%2C50%2C40%2C110&SHORTNAME=GPM_3IMERGDL&DATASET_VERSION=07&LABEL=3B-DAY-L.MS.MRG.3IMERG.20250906-S000000-E235959.V07B.nc4.SUB.nc4&VERSION=1.02&SERVICE=L34RS_GPM",

    "https://gpm1.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FGPM_L3%2FGPM_3IMERGDL.07%2F2025%2F09%2F3B-DAY-L.MS.MRG.3IMERG.20250907-S000000-E235959.V07B.nc4&VARIABLES=precipitation&FORMAT=bmM0Lw&BBOX=-10%2C50%2C40%2C110&SHORTNAME=GPM_3IMERGDL&DATASET_VERSION=07&LABEL=3B-DAY-L.MS.MRG.3IMERG.20250907-S000000-E235959.V07B.nc4.SUB.nc4&VERSION=1.02&SERVICE=L34RS_GPM",

    "https://gpm1.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FGPM_L3%2FGPM_3IMERGDL.07%2F2025%2F09%2F3B-DAY-L.MS.MRG.3IMERG.20250908-S000000-E235959.V07B.nc4&VARIABLES=precipitation&FORMAT=bmM0Lw&BBOX=-10%2C50%2C40%2C110&SHORTNAME=GPM_3IMERGDL&DATASET_VERSION=07&LABEL=3B-DAY-L.MS.MRG.3IMERG.20250908-S000000-E235959.V07B.nc4.SUB.nc4&VERSION=1.02&SERVICE=L34RS_GPM"
]

import subprocess

for url in links:
    cmd = [
        "wget",
        "--load-cookies", "/root/cookies.txt",
        "--save-cookies", "/root/cookies.txt",
        "--keep-session-cookies",
        "--content-disposition",
        url
    ]

    subprocess.run(cmd, check=False)

!ls -lh *.nc4

import netCDF4 as nc
import numpy as np

# Read the NetCDF file
file_path = '/content/3B-DAY-L.MS.MRG.3IMERG.20250901-S000000-E235959.V07B.nc4.SUB.nc4'
dataset = nc.Dataset(file_path, 'r')

print("=" * 80)
print("FILE DETAILS")
print("=" * 80)

# Global attributes
print("\n--- GLOBAL ATTRIBUTES ---")
for attr in dataset.ncattrs():
    print(f"{attr}: {dataset.getncattr(attr)}")

# Dimensions
print("\n--- DIMENSIONS ---")
for dim_name, dim in dataset.dimensions.items():
    print(f"{dim_name}: {len(dim)} {'(unlimited)' if dim.isunlimited() else ''}")

# Variables
print("\n--- VARIABLES ---")
for var_name, var in dataset.variables.items():
    print(f"\n{var_name}:")
    print(f"  Shape: {var.shape}")
    print(f"  Data type: {var.dtype}")
    print(f"  Dimensions: {var.dimensions}")

    # Variable attributes
    if var.ncattrs():
        print(f"  Attributes:")
        for attr in var.ncattrs():
            print(f"    {attr}: {var.getncattr(attr)}")

    # Show data range for numeric variables
    if var.size > 0 and np.issubdtype(var.dtype, np.number):
        try:
            data = var[:]
            valid_data = data[~np.isnan(data)] if np.issubdtype(data.dtype, np.floating) else data
            if len(valid_data) > 0:
                print(f"  Data range: [{np.min(valid_data):.4f}, {np.max(valid_data):.4f}]")
        except:
            pass

# Groups (if any)
if dataset.groups:
    print("\n--- GROUPS ---")
    for group_name in dataset.groups:
        print(f"{group_name}")

print("\n" + "=" * 80)
print("FILE STRUCTURE SUMMARY")
print("=" * 80)
print(f"Total variables: {len(dataset.variables)}")
print(f"Total dimensions: {len(dataset.dimensions)}")
print(f"Total global attributes: {len(dataset.ncattrs())}")

# Close the dataset
dataset.close()
print("\nFile closed successfully.")

!pip install cartopy -q

# ==============================
# IMERG Daily Rainfall (8-day layout)
# Sri Lanka cropped region
# ==============================

import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib.colors import ListedColormap, BoundaryNorm
import glob
import os

# ------------------------------
# Sri Lanka boundaries
# ------------------------------
LON_MIN, LON_MAX = 76, 86
LAT_MIN, LAT_MAX = 2, 12

# ------------------------------
# Get all files (sorted)
# ------------------------------
files = sorted(glob.glob("/content/3B-DAY-L.MS.MRG.3IMERG.202509*.nc4.SUB.nc4"))

# ------------------------------
# Discrete rainfall classes
# ------------------------------
levels = [0, 1, 5, 10, 20, 50, 100, 200, 300]
colors = [
    "#f7fbff", "#deebf7", "#9ecae1", "#6baed6",
    "#3182bd", "#08519c", "#08306b", "#4a1486"
]
cmap = ListedColormap(colors)
norm = BoundaryNorm(levels, cmap.N)

# ------------------------------
# Create subplot layout (4x2)
# ------------------------------
fig, axes = plt.subplots(
    nrows=4, ncols=2,
    figsize=(12, 16),
    subplot_kw={"projection": ccrs.PlateCarree()}
)
axes = axes.flatten()

# ------------------------------
# Plot loop
# ------------------------------
for ax, file in zip(axes, files):
    ds = xr.open_dataset(file)

    # ---- Crop to Sri Lanka BEFORE plotting ----
    ds = ds.sel(
        lon=slice(LON_MIN, LON_MAX),
        lat=slice(LAT_MIN, LAT_MAX)
    )

    rain = ds["precipitation"].isel(time=0)
    rain = rain.where(rain > 0)

    date_str = os.path.basename(file).split(".")[4][:8]

    mesh = ax.pcolormesh(
        ds["lon"],
        ds["lat"],
        rain.T,
        cmap=cmap,
        norm=norm,
        shading="auto"
    )

    ax.coastlines(resolution="10m")
    ax.add_feature(cfeature.BORDERS, linewidth=0.4)

    ax.set_extent(
        [LON_MIN, LON_MAX, LAT_MIN, LAT_MAX],
        crs=ccrs.PlateCarree()
    )

    ax.set_title(date_str, fontsize=10)

# ------------------------------
# Vertical colorbar (RIGHT SIDE)
# ------------------------------
cbar = fig.colorbar(
    mesh,
    ax=axes,
    orientation="vertical",
    fraction=0.03,
    pad=0.04,
    ticks=levels
)
cbar.set_label("Daily Rainfall (mm/day)")

# ------------------------------
# Main title & layout
# ------------------------------
fig.suptitle(
    "IMERG Daily Rainfall (Discrete Classes)\nSri Lanka (76–86°E, 2–12°N) | 1–8 Sep 2025",
    fontsize=14
)

plt.tight_layout(rect=[0, 0, 0.90, 0.95])
plt.show()